name: care_betes
description: A new Flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  mobx: ^2.2.0
  flutter_modular: ^6.3.2
  flutter_mobx: ^2.1.0
  sqlite3: ^2.1.0
  path: ^1.8.3
  sqflite: ^2.3.0
  shared_preferences: ^2.2.1
  floating_action_bubble: ^1.1.4
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  module:
    androidX: true
    androidPackage: br.com.eduprog.care_betes
    iosBundleIdentifier: br.com.eduprog.careBetes

flutter_native_splash:
  color: "#7EA1C1"
  images: "assets/images/logo_bete.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/logo_bete.png"
  android: true
  ios: true
  remove_alpha_ios: true